### PR TITLE
Fix race condition in `ListenableFutureTest.testFutureIsDoneAfterChildrenCompleted`.

### PR DESCRIPTION
**Pull request by chaoren**
The `foo` coroutine could be cancelled before it's started, which would immediately trigger the `expect(3)` in `foo.invokeOnCompletion`. This could happen before `expect(2)` and fail the test.

### CODE REVIEW

**Review by dkhalanskyjb — CHANGES_REQUESTED** [review]
Why do you consider this a problem? I think that the test should pass either way, whether `foo` starts or not. For example, if we replace the future's body with this:
```kotlin
            val bar = async<Int> { throw testException }
            try {
                bar.await()
            } finally {
                val foo = async {
                    try {
                        delay(Long.MAX_VALUE)
                        42
                    } finally {
                        withContext(NonCancellable) {
                            delay(200)
                        }
                    }
                }
                foo.invokeOnCompletion {
                    expect(3)
                }
            }
```
then `foo` never starts, but the test still passes.

**Comment by chaoren** [comment]
If `foo` is cancelled before it's started, then `foo.invokeOnCompletion` is immediately triggered and `expect(3)` happens, which could happen before `expect(2)`. The only thing making sure that `expect(3)` appears after `expect(2)` is the `delay(200)` in `foo`.

**Comment by chaoren** [comment]
I've noticed that the test is consistently flaky if you run it on a machine with very few cores.

**Comment by dkhalanskyjb** [comment]
Oh, okay, got it, thanks. Could you make this dependency explicit, then, by adding a `CountDownLatch(1)`? `withContext(NonCancellable) { delay(200) }` would be replaced with awaiting the latch, and we'd count down the latch after `expect(2)`.

**Comment by chaoren** [comment]
Done.

**Review by dkhalanskyjb — APPROVED** [review]
Well done, thanks!

**Pull request merged**
