### PR TITLE
Use our consistent code style in ThreadContextElement documentation

### PR DESCRIPTION
**Pull request by qwwdfsad**

### CODE REVIEW

**Review by dkhalanskyjb — COMMENTED** [review]
Added a commit with some more indentation fixes. We can revert the commit and make it a separate PR if you want.

Also, shouldn't this be targeting `master`?

**Comment by qwwdfsad** [comment]
Works for me, thanks! (I cannot review it as the author)
This one does not bring much of a value in the moment, so decided to go for `develop` as it was a bit easier

**Comment by qwwdfsad** [comment]
Do you mind if I merge it as is to `develop`?

**Review by dkhalanskyjb — APPROVED** [review]
I don't mind.

**Pull request merged**
