### PR TITLE
fix: remove `sampleStart` and `sampleEnd` comments from example in coroutine-context-and-dispatchers.md

### PR DESCRIPTION
**Pull request by PetrakovichVictoria**
https://kotlinlang.org/docs/coroutine-context-and-dispatchers.html#jumping-between-threads

UPD: removed sampleStart and sampleEnd comments.

Fix this sample not being runnable:
Screenshot 2024-04-02 at 13 00 09

### CODE REVIEW

**Review by danil-pavlov — APPROVED** [review]

**Comment by dkhalanskyjb** [comment]
This example isn't running correctly, but fails with
```
Exception in thread "main" java.security.AccessControlException: Access control exception due to security reasons in web playground: 
 access denied ("java.lang.RuntimePermission" "modifyThread")
 at java.lang.SecurityManager.checkPermission (:-1) 
```

**Comment by PetrakovichVictoria** [comment]
I don't know if the problem is in the coroutines here or in some restrictions in the playground. Maybe it's just worth deleting //sampleStart and sampleEnd comments and making this example non-runnable.

**Comment by dkhalanskyjb** [comment]
This example is being run as part of our tests (https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/jvm/test/guide/test/DispatcherGuideTest.kt#L37-L44); so, these are probably just the playground restrictions. Also, making the example non-runnable would remove the test automatically, and I don't think we want that.

**Comment by qwwdfsad** [comment]
It's https://youtrack.jetbrains.com/issue/KTL-108 unfortunately

**Comment by PetrakovichVictoria** [comment]
> This example is being run as part of our tests

I also launched it before I created this PR: locally, this example passes w/o problems. 

> Also, making the example non-runnable would remove the test automatically, and I don't think we want that.

1. Having sampleStart and sampleEnd shows an initial will for this example to be runnable. 
2. Almost all other examples from this page work (except [here](https://kotlinlang.org/docs/coroutine-context-and-dispatchers.html#coroutine-scope) because these ones show some thought in general). So, having this one example non-runnable seems strange twice. 
3. For me, it's not that much important will it be runnable or not, but I suppose, if we want to leave it non-runnable, then `//sampleStart` and `//sampleEnd` should be removed (and the runnability marker too). I can do this if you wish.

**Comment by PetrakovichVictoria** [comment]
I don't see any changes after running knit locally. Removed runnability and sample start/end comments.

**Comment by dkhalanskyjb** [comment]
Thanks!

**Pull request merged**
