### PR TITLE
- add 32bit

### PR DESCRIPTION
**Pull request by danielgruber**
Add 32 bit with #2157

### CODE REVIEW

**Comment by elizarov** [comment]
Does it actually work? Would the tests run on a 64bit version of windows?

**Comment by elizarov** [comment]
It does not build at our CI: https://teamcity.jetbrains.com/buildConfiguration/KotlinTools_KotlinxCoroutines_BuildWindows/3042932

**Comment by danielgruber** [comment]
weird. Would you help me in one thing: Where do the presets come from? So how do I need to define a new Win32 preset? Though this comes from Multiplatform Library core, but seems like it doesn't as it does not find the minwx86 preset although it should support it? :)

**Comment by danielgruber** [comment]
I fixed the Typo, but I think it's still depending on AtomicFus Pull Request first: https://github.com/Kotlin/kotlinx.atomicfu/pull/146

**Review by qwwdfsad — COMMENTED** [review]
Alas, we are not _yet_ ready to enable new Native targets.
We are working on the list with full Kotlin/Native-wide list of various targets support (debugging support/unit testing support/whether we test our libraries on a specific target and so on) and as soon as it's ready, we'll enable _all_ existing targets, referencing a giving guarantees

**Pull request closed without merging**
