### PR TITLE
Kts transition

### PR DESCRIPTION
**Pull request by qwwdfsad**

### CODE REVIEW

**Comment by turansky** [comment]
@qwwdfsad Will it be merged in `develop`?

**Comment by turansky** [comment]
@qwwdfsad Will it be merged in `develop` berfore Kotlin `1.4` release?

**Comment by qwwdfsad** [comment]
@turansky unfortunately, no, we still have too many breaking changes and overwhelmed with other work to do :(

**Comment by qwwdfsad** [comment]
Huge thanks for your contribution and sorry for the long delay!
Merged manually here: #2216

**Pull request closed without merging**
