### PR TITLE
Remove SubscriptionReceiveChannel

### PR DESCRIPTION
**Pull request by deva666**
#283 Issue says that `SubscriptionReceiveChannel` should be removed, so this PR is a breaking change. Not sure if this is wanted?

### CODE REVIEW

**Comment by elizarov** [comment]
That is Ok. It is supposed to be breaking change in the source. However, for binary compatibility we need to keep old `SubscrpitonReceiveChannel` interface (as deprecated), keep old `openSubscription` function (as deprecated/hidden), so new `openSubscription` will probably have to use a different `@JvmName`.

Also, can you please rebase your changes onto the latest `develop` branch.

**Comment by deva666** [comment]
@elizarov not sure how you can apply `JvmName` annotation in this case. And of course, there can't be two functions with different return types. If we deprecate the old `openSubscription` function can the new one be named differently, something like `openReceiveChannel` ?

**Comment by elizarov** [comment]
Hm... I checked. Indeed, I cannot seem to find a way to preserve binary compatibility when changing return type. This is bad: https://youtrack.jetbrains.com/issue/KT-23750

**Comment by elizarov** [comment]
I've found a way to preserve binary compatibility. Merged this PR into `develop`.

**Pull request closed without merging**
