### PR TITLE
Release candidate

### PR DESCRIPTION
**Pull request by qwwdfsad**
From branch `ea13`.

* Migration to Kotlin 1.3
* All deprecated API is removed
* Internal API became `internal` where it is possible
* Some workarounds for compiler bugs are removed
* Coroutines API annotations are `@Experimental`

### CODE REVIEW

**Comment by elizarov** [comment]
We need to check `ktor` against this RC to make sure nothing extra was removed.

**Comment by qwwdfsad** [comment]
Will check against Ktor (already checked `kotlinx.io`) before merge

**Comment by elizarov** [comment]
`ExecutorService.asCoroutineDispatcher` shall have `@JvmName("from")`, too.

**Comment by elizarov** [comment]
For consistency, we should have `@JvmName("from")` on `ThreadLocal.asContextElement`, too.

**Comment by elizarov** [comment]
Looks good for me now.

**Pull request merged**
