### PR TITLE
Split main coroutines guide into multiple files

### PR DESCRIPTION
**Pull request by hhariri**

### CODE REVIEW

**Comment by elizarov** [comment]
A few notes:
1. Root `coroutines-guide.md` should have one-line note that it had moved and a link to `docs/coroutines-guide.md`
2. `docs/coroutines-guide.md` should contain references to chapters.
We'll need to merge this spit asap, before it starts syncing to the website, because we might need to cleanup some links and references from the guide to the deprecated APIs (it is not a concern for cores APIs like launch, but there are a few touches around channels).

**Comment by elizarov** [comment]
6. `testKotlinxCoroutinesExperimentalGuideChannel04` is failing because of the lost code line in `channels.md` (see line 159)

**Comment by elizarov** [comment]
7. `testKotlinxCoroutinesExperimentalGuideContext09` is failing because it had a minor bug in the original `coroutines-guide.md`. Please, rebase to the latest `develop` and at a look a the history of changes of `coroutines-guide.md` -- there was a fix in this commit: https://github.com/elizarov/kotlinx.coroutines/commit/bca98f4e9ea3c485c8691209be32fee487f812fe#diff-5fe5ce11a5eefa64d0e69920088c5775

**Comment by hhariri** [comment]
@elizarov unless  I messed something up, all changes requested are done and rebased with develop branch. Thanks.

**Comment by gildor** [comment]
Does this refactoring of coroutine docs includes merging with https://github.com/Kotlin/kotlin-coroutines/blob/master/kotlin-coroutines-informal.md?

This document still contains a lot of useful information (especially example of wrapping callbacks to coroutines)
I understand that thia document is not directly related on kotlinx.coroutines, but I think that it would be good to show point on kotlinx.coroutines as reference implementation.

**Pull request merged**
