### PR TITLE
Future.kt: add `mayInterruptIfRunning` flag to `await()`

### PR DESCRIPTION
**Pull request by revintec**

### CODE REVIEW

**Comment by revintec** [comment]
may need `@JvmOverloads` or `await()=await(false)` for compatibility sake, please make suggestion if we need that and if so, which one to use. MR made modifiable, feel free to add the code

**Comment by dkhalanskyjb** [comment]
1. Please base the PR on the `develop` branch. See https://github.com/Kotlin/kotlinx.coroutines/blob/master/CONTRIBUTING.md.
2. Ensure that your project successfully builds. Currently, it fails with the `apiCheck` task. The task also shows whether the changes you make are backward compatible.
3. Changes should be accompanied by tests.
4. And documentation.

**Comment by qwwdfsad** [comment]
Contribution guide aside, this change was already discussed: https://github.com/Kotlin/kotlinx.coroutines/issues/259

The resolution is "won't fix" because this flag has no effect

**Comment by revintec** [comment]
sorry I violated the Contribution Guide. It seems that I can't change the merge target branch, maybe because this MR is closed?
let's continue discuss in #259

**Comment by dkhalanskyjb** [comment]
The merge target branch can't be changed for existing pull requests, you'll need to open a new one. Though, yes, let's discuss it first.

**Pull request closed without merging**
