### PR TITLE
Make FlowCollector fun interface, remove redundant extensions

### PR DESCRIPTION
**Pull request by qwwdfsad**
* It also saves us from copy-without-imports problem

Addresses #3037

### CODE REVIEW

**Review by dkhalanskyjb — APPROVED** [review]
Found two implementations of `FlowCollector`.
* `Collect.kt`. That implementation can be replaced with
```kotlin
public suspend inline fun <T> Flow<T>.collectIndexed(crossinline action: suspend (index: Int, value: T) -> Unit) {
    var index = 0
    collect { value ->
        action(checkIndexOverflow(index++), value)
    }
}
```
* `Limit.kt`. Doesn't simplify easily.
* In benchmarks, `FlowPlaysScrabbleOpt`. Simplifies easily.

These simplifications are not obviously better, so it's up to you whether to make them.

**Comment by qwwdfsad** [comment]
I've deliberately avoided touching benchmarks.
Regarding `collectIndexed` -- the proposed implementation is not identical, capturing mutable ints will be boxed on each emission, while spilling it into the state of flow collector explicitly leaves it as `int` type

**Comment by olme04** [comment]
Looks like after this change, coroutines 1.6.0 isn't backward compatible, when `Flow<T>.collect(action)` used in library. Is it expected?

**Comment by zjuhasz** [comment]
This change makes  the documentation confusing in some places.

In `SharedFlow.collect` it says "To emit values from a shared flow into a specific collector ... collect { ... } extension should be used." but collect extension no longer exists.

In `Flow.collect` it says "To ensure the context preservation property, it is not recommended implementing this method directly. Instead, AbstractFlow can be used as the base type to properly ensure flow's properties." but every time a call to collect is made on any Flow we're anonymously implementing collect directly, usually with the SAM conversion.

**Comment by qwwdfsad** [comment]
@zjuhasz thanks for noticing, shared flow documentation is fixed in #3127

> but every time a call to collect is made on any Flow we're anonymously implementing collect directly, usually with the SAM conversion.

`Flow` interface is not anonymously implemented during `collect` SAM-conversion, only `FlowCollector` is, which is perfectly safe

**Pull request merged**
