### PR TITLE
ProGuard config

### PR DESCRIPTION
**Pull request by Miha-x64**
Fixes https://github.com/Kotlin/kotlinx.coroutines/issues/103,
suggested by ProGuard team here: https://sourceforge.net/p/proguard/bugs/660/

### CODE REVIEW

**Comment by cypressious** [comment]
If the `kotlinx-coroutines-android` project were an AAR artifact, you could directly bundle the rules.

**Comment by Miha-x64** [comment]
@cypressious I don't think it's very useful.
Also, bad ProGuard rules lead to such hacks:
image

**Comment by JakeWharton** [comment]
This is way too broad. You only want to prevent their renaming while currently it will also prevent their removal when unused.

**Comment by Miha-x64** [comment]
@JakeWharton 
> [-keepclassmembernames class_specification](https://www.guardsquare.com/en/proguard/manual/usage#keepclassmembernames)
> Specifies class members whose names are to be preserved, if they aren't removed in the shrinking phase.

**Comment by JakeWharton** [comment]
Perfect. Thought it said keepclassmembers

**Pull request merged**
