### PR TITLE
suggested update to SharedFlow.kt

### PR DESCRIPTION
**Pull request by Nodrex**
Coroutines and Flows are amazing I love them and many many thanks for them 🤩🤩🤩🤩 You guys in JetBrains rock 🤘🤘🤘 🚀🚀🚀
I have a small suggestion:
According to this big discussion: 
https://github.com/Kotlin/kotlinx.coroutines/issues/2387  and a lot of confusion, including myself, default value of `extraBufferCapacity` should be 1 instead of 0 and I think this parameter also needs better explanation

### CODE REVIEW

**Comment by qwwdfsad** [comment]
Thanks!

Unfortunately, we cannot accept this contribution -- it is a breaking change for stable API that will break almost every client of `MutableSharedFlow` on update.
The best way to affect the current behaviour is to initiate a discussion and maybe propose a draft solution/idea, as well as outline the downsides of the current behaviour and why the proposed solution outweighs **benefits** of the current solution

**Comment by Nodrex** [comment]
At least we can update docs, cause `onBufferOverflow` can be used to control backpressure on emitters (slowing them down). Is it not?

**Comment by qwwdfsad** [comment]
Yes, it probably makes sense

**Comment by Nodrex** [comment]
So should I send another pull request with just doc changes?

**Pull request closed without merging**
