### PR TITLE
implementation of a SLF4J MDC context

### PR DESCRIPTION
**Pull request by abendt**
We use the CoRoutines rxjava integration and stumbled across the necessity to make the SLF4J MDC Context within in the CoRoutine scope. We implemented a solution based on the the description here:
https://github.com/Kotlin/kotlinx.coroutines/issues/119

### CODE REVIEW

**Comment by oshai** [comment]
In case this is merged will add it to [kotlin-logging](https://github.com/MicroUtils/kotlin-logging) docs

**Comment by x0a1b** [comment]
I think it's a really useful addition I am not sure if this change should be merged here or go to Kotlin-logging (unless it's using some internal classes from coroutines). I strongly think getting it in kotlin-logging rather than in core is the right option; and would let us iterate faster.

**Comment by abendt** [comment]
fair enough, i created the PR here because of the suggestion of @elizarov: https://github.com/Kotlin/kotlinx.coroutines/issues/119
kotlin-logging also looks like a reasonable location

**Comment by oshai** [comment]
I think that both here and in kotlin-logging this will be an integration module. @elizarov suggested: "We should really have it out-of-the box in a separate integration module." in #119 . 
In addition, kotlinx.coroutines already has other integration modules that are similar so it seems like a more natural place to look for, and also a case for example for the lib users.

**Comment by elizarov** [comment]
I've rebased your code on top of new architecture to introduce thread-local context elements as explained in #119 and opened a new PR #455

**Pull request closed without merging**
