### PR TITLE
Fix expect/actual mismatched member scope for `open expect` compilati…

### PR DESCRIPTION
**Pull request by nikitabobko**
…on errors

Those are compilation errors introduced in Kotlin 1.9.20 in scope of https://youtrack.jetbrains.com/issue/KT-22841

### CODE REVIEW

**Comment by nikitabobko** [comment]
Don't review it yet. The PR is in progress

**Comment by nikitabobko** [comment]
Main review in kotlin: https://jetbrains.team/p/kt/reviews/11603/timeline

**Comment by qwwdfsad** [comment]
>Don't review it yet. The PR is in progress.

You can use "Open draft pull request" and promote it to the PR when it's ready: 
image

**Comment by nikitabobko** [comment]
Ready to review

**Review by qwwdfsad — COMMENTED** [review]
Is it correct that each of the ~10 suppresses should be replaced with `AllowDifferentMembersInActual` in 1.9.20?

Feels like there are a bit too much of suppresses

**Comment by nikitabobko** [comment]
> Is it correct that each of the ~10 suppresses should be replaced with AllowDifferentMembersInActual in 1.9.20?

Yes, it's correct

> Feels like there are a bit too much of suppresses

Yes, that's true. Unfortunately, we don't have any consistent design ready for the non-final expect class https://youtrack.jetbrains.com/issue/KT-22841

That's why we have no choice but to prohibit different member scopes for non-final `open` `expect class` and its appropriate `actual class`. We discussed that it will break a lot of code during the design meeting

**Review by qwwdfsad — APPROVED** [review]

**Pull request merged**
