### PR TITLE
efficient read-write lock (#94) and semaphore implementations

### PR DESCRIPTION
**Pull request by btwilk**
These read-write lock and semaphore implementations are completely non-suspending in happy cases: i.e., when there are no writers or when permits are available.

The implementations are missing support for select, graceful handling of cancellation, ownership tracking, and stack-overflow avoidance for the Unconfined dispatcher.

This contribution includes a StateMachine abstraction which encapsulates a lot of the complexity of both implementations. It could eventually be used to simplify Mutex as well.

Addresses issue #94.

### CODE REVIEW

**Comment by bohsen** [comment]
No tests?

**Comment by btwilk** [comment]
Is there anything I can do to attract a reviewer for this PR?

**Comment by elizarov** [comment]
P.S. Please, squash your contribution into a single commit to make it easier to review.

**Comment by elizarov** [comment]
As for specific comments:

1. There is no need for a new `Lock` interface. We already have `Mutex` interface in this library. We only need `ReadWriteMutex` (that is how it should be named). The `Lock` name would conflict with `java.util.concurrent.locks.Lock`.

2. There is not need for a dedicated `StateMachine` class that boxes atomic ref inside of it. You can simply define `transition` function as an extension function on `AtomicRef<Any>` type. I found actually recommend to use any existing `loop` and `update` extension functions on `AtomicRef`. You don't need `Decision.Stay` and you can always just do a non-local return from an enclosing function. The whole `Decision` class (and the overhead with creation of its instances) should be removed. 

3. Please, abstract away all the existing tests on `Mutex` implementation and make sure that all pass on the `write` part of `ReadWrite` mutex and on the 0/1 `Semaphore` as well.

4. The code and tests shall be placed into `kotlinx-coroutines-core-common` module. It shall pass all the test both on Kotlin/JVM and on Kotlin/JS.

**Comment by btwilk** [comment]
Thanks for the feedback. I switched to using the Mutex interface and the loop method of AtomicRef as in MutexImpl.

For the read lock I'm just throwing exceptions for anything related to owners.

I'm not too happy with how I addressed 3 as I had to override some of the tests for certain implementations. Let me know if you have any better ideas.

**Comment by clarcharr** [comment]
This is awesome; thank you for the hard work! Any idea when this will be done/merged?

**Comment by clarcharr** [comment]
Any plans to work on this soon?

**Comment by btwilk** [comment]
I'm ready to make more progress if I get some more guidance on requirements.

**Comment by qwwdfsad** [comment]
I am sorry for this delay; I will try to spend more time on reviewing PRs or at least on providing feedback as soon as possible even if the issue is not on the priority list.

Do you still want to work on this PR?
If so, please rebase on current`develop` branch and I will review it.

I apologize for this delay.

**Pull request closed without merging**
