### PR TITLE
Cover all publications in bom

### PR DESCRIPTION
**Pull request by Prototik**
Currently kx-coroutines-core-{common,js,native} publications missing

### CODE REVIEW

**Comment by Prototik** [comment]
But BOMs can be applied at any project, not only jvm-only. If I want to build kotlin/js module it still valid to use bom for dependency resolution, isn't it?

So BOMs isn't bound to jvm world, it just used to resolve correct versions of libraries.

[Kotlin itself](https://github.com/JetBrains/kotlin/blob/master/libraries/tools/kotlin-bom/pom.xml) provides js/common artifacts too

**Comment by Prototik** [comment]
@qwwdfsad any info?

**Comment by qwwdfsad** [comment]
I will merge your PR soon, your concerns regarding non-jvm usages are completely valid.

>Also discovered that io.spring.dependency-management could be replaces with built-in gradle java-platform plugin (with rich gradle metadata info), but that requires gradle 5.2

Thanks for the info! We hopefully update to Gradle 5.2 as soon as figure out what to do with Gradle metadata.

**Comment by qwwdfsad** [comment]
Great job, thanks!

**Pull request merged**
