### PR TITLE
Make use of `CompletionStage#handle` instead of `whenComplete`.

### PR DESCRIPTION
**Pull request by He-Pin**
Which leads a better performance.
https://github.com/line/armeria/pull/1440
https://github.com/akka/akka/pull/31283

### CODE REVIEW

**Review by qwwdfsad — CHANGES_REQUESTED** [review]
I've checked the implementation of `uniWhenCompleteStage` and it seems like the issue described in Akka/armeria is only applicable for `*Async` methods, not to regular ones.

I've also benchmarked the simplest `asCompletableFuture` and `future{}` builders and found no difference.

Taking into account that `handle` is semantically heavier than `when*` as it returns new value and potentially can change the result of the computation when used carelessly, it would be nice to see a benchmark that shows that this change yields a performance improvement prior to merge.

Code-wise changes looks good

**Comment by He-Pin** [comment]
@qwwdfsad this link https://github.com/line/armeria/pull/1444, `handle` helps especially when the CompletionStage is failed.

**Comment by He-Pin** [comment]
I will submit an jmh bench later。

**Comment by He-Pin** [comment]
image

jmh:run -i 5 -wi 5 -f1 -t1 .CompletionStageBenchmark.

**Review by qwwdfsad — APPROVED** [review]
Thanks!

**Comment by qwwdfsad** [comment]
Please rebase your PR on `develop` branch and change the target branch to `develop` as well

**Comment by He-Pin** [comment]
Have rebased on to the `develop` and retarget `develop` branch.

**Review by qwwdfsad — APPROVED** [review]
Thanks!

**Pull request merged**
