### PR TITLE
Combine perf

### PR DESCRIPTION
**Pull request by joe198**
ok

### CODE REVIEW

**Comment by joe198** [comment]
upgraded

**Review by joe198 — COMMENTED** [review]
ok,

**Comment by joe198** [comment]
upgraded branch

**Comment by qwwdfsad** [comment]
Thanks for the effort, but this is my in-progress branch and I will open PR when it's ready.
If you are willing to contribute, please follow our [contribution guide](https://github.com/Kotlin/kotlinx.coroutines/blob/master/CONTRIBUTING.md)

**Pull request closed without merging**
