### PR TITLE
Preserve binary compatibility with `TestScope.runTest(Long)`

### LINKED ISSUE #3673: 1.7.0-Beta: NoSuchMethodError: void kotlinx.coroutines.test.TestBuildersKt.runTest$default(kotlinx.coroutines.test.TestScope, long, kotlin.jvm.functions.Function2, int, java.lang.Object)
**Describe the bug**

When updating a project to use `kotlinx.coroutines` `1.7.0-Beta`, existing tests fail with a `NoSuchMethodError` for a `runTest` that's being called internally by the Compose test utilities.

The full stack trace looks like the following (but fail for every Compose test):

```
com.alexvanyo.composelife.resourcestate.ResourceStateComposableTests > collect_as_state_is_correct FAILED
    java.lang.NoSuchMethodError: 'void kotlinx.coroutines.test.TestBuildersKt.runTest$default(kotlinx.coroutines.test.TestScope, long, kotlin.jvm.functions.Function2, int, java.lang.Object)'
        at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withTestCoroutines(ComposeUiTest.android.kt:342)
        at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withTestCoroutines(ComposeUiTest.android.kt:218)
        at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1.invoke(ComposeUiTest.android.kt:294)
        at androidx.compose.ui.test.junit4.IdlingStrategy.withStrategy(IdlingStrategy.android.kt:52)
        at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1.invoke(ComposeUiTest.android.kt:293)
        at androidx.compose.ui.test.junit4.IdlingResourceRegistry.withRegistry(IdlingResourceRegistry.jvm.kt:157)
        at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1.invoke(ComposeUiTest.android.kt:292)
        at androidx.compose.ui.test.junit4.ComposeRootRegistry.withRegistry(ComposeRootRegistry.android.kt:146)
        at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.runTest(ComposeUiTest.android.kt:291)
        at androidx.compose.ui.test.ComposeUiTest_androidKt.runAndroidComposeUiTest(ComposeUiTest.android.kt:107)
        at androidx.compose.ui.test.ComposeUiTest_androidKt.runComposeUiTest(ComposeUiTest.android.kt:63)
        at com.alexvanyo.composelife.resourcestate.ResourceStateComposableTests.collect_as_state_is_correct(ResourceStateComposableTests.kt:39)
```

**Provide a Reproducer**

Reproducing PR: https://github.com/alexvanyo/composelife/pull/838

It looks like the update to `runTest` in `1.7.0-Beta` might not have been binary compatible?

### PR DESCRIPTION
**Pull request by dkhalanskyjb**
Fixes #3673

### CODE REVIEW

**Comment by qwwdfsad** [comment]
Shouldn't it target `develop`?

**Comment by dkhalanskyjb** [comment]
It should.

**Review by qwwdfsad — APPROVED** [review]

**Comment by qwwdfsad** [comment]
On the one hand, I'm delighted to know that `kotlinx-coroutines-test` provides enough value to be used in compose test utilities even in its experimental state. On the other hand, it's a bit terrifying as we have to care about backwards compatibility _for experimental_ API even more

**Comment by dkhalanskyjb** [comment]
Yeah, I, too, was taken aback. I knew people depended on experimental functions, but I thought the experimental + tests would be the one area where production-like stability guarantees are unnecessary. Alas, we seem to be firmly in the https://xkcd.com/1172/ territory.

**Comment by arkivanov** [comment]
Perhaps, a library shouldn't use any experimental API, to avoid this kind of problems? Unless the library itself is experimental.

**Comment by qwwdfsad** [comment]
Depends on the library. It's okay to use it as long all available API depending on this API is also marked experimental.

For example, we had a stable `delay(long)` function and `@ExperimentalStdlibApi delay(Duration)` when duration was experimental.

**Pull request merged**
