### PR TITLE
Make Dispatchers.setMain affect all delays in tests.

### PR DESCRIPTION
**Pull request by dkhalanskyjb**
Option 2.

### CODE REVIEW

**Review by qwwdfsad — COMMENTED** [review]
I'm a bit concerned this is way too intrusive change with potentially non-trivial interactions with existing/running code (e.g. now the source of default delay can be changed on the fly).

If you do not have objections, I would prefer sticking with option 1 for the initial release

**Comment by dkhalanskyjb** [comment]
I would also prefer the first option initially, at least until we deal with the initial feedback on both the updated test framework and the change to the default delay. Otherwise, the changes could just be too overwhelming: it's not easy now to diagnose the situation where the default delay is not used for some reason, and the consequences of entering such a situation would become much more significant.

That said, I'd argued that, in code that's heavily using `Dispatchers.Main`, the problem of non-trivial interactions is already just as pronounced, as the only place where the default delay could change is in `setMain`.

**Comment by dkhalanskyjb** [comment]
#3094 contains some examples of when delay-skipping is undesirable in tests.

**Comment by 1zaman** [comment]
This might cause similar issues as in #3173, with actual test infrastructure delays being controlled by the test dispatcher. Perhaps this can be addressed by using another delay-handling dispatcher to run delays in the test infrastructure, as [planned](https://github.com/cashapp/turbine/issues/71) by the Turbine library.

Note that as described in #3173, `Dispatchers.setMain` already affects all delays in Robolectric tests, which causes inconsistencies with non-Robolectric tests.

**Comment by qwwdfsad** [comment]
This PR can be now closed, can't it?

**Comment by dkhalanskyjb** [comment]
Sure.

**Pull request closed without merging**
