### PR TITLE
Update example Android apps toolchain (AGP 3.5.0, AndroidX)

### PR DESCRIPTION
**Pull request by elizarov**
* Gradle 5.4.1
* AGP 3.5.0
* Migrated to AndroidX
* Updated versions of all dependencies to the most recent ones
* Removed proguard rules

### CODE REVIEW

**Comment by KaiyuanZhao** [comment]
hi @elizarov 
ui/kotlinx-coroutines-android/build.gradle is still using com.android.support:support-annotations:$android_support_version

**Comment by elizarov** [comment]
@KaiyuanZhao what should it use instead?

**Comment by KaiyuanZhao** [comment]
@elizarov use `androidx.annotation:annotation` instead of support. This is the full [mapping](https://developer.android.com/jetpack/androidx/migrate/artifact-mappings)

**Comment by elizarov** [comment]
Tried it. Cannot find `androidx.annotation:annotation` artifact in any of the repositories we are using in our build (including a google repo).

**Comment by KaiyuanZhao** [comment]
@elizarov Did you add version after `annotation`? The full dependency notation is `androidx.annotation:annotation:1.1.0`

**Comment by KaiyuanZhao** [comment]
@elizarov Androidx annotation document is in [this link](https://developer.android.com/jetpack/androidx/releases/annotation). And this artifact is in [google repo](https://developer.android.com/studio/build/dependencies#google-maven).

**Comment by elizarov** [comment]
Thanks. See #1932

**Pull request merged**
