### PR TITLE
fix asFlow blocking thread

### PR DESCRIPTION
**Pull request by Ericliu001**
Fixes the issue https://github.com/Kotlin/kotlinx.coroutines/issues/3979 

Changes the ChannelFlow's buffer to UNLIMITED when asFlow() is called

### CODE REVIEW

**Comment by dkhalanskyjb** [comment]
This PR does not respect the contribution guidelines (https://github.com/Kotlin/kotlinx.coroutines/blob/master/CONTRIBUTING.md#submitting-prs), but more importantly, it's also not the change we'd like to introduce, as this can easily be expressed already by applying `buffer()`.

**Comment by Ericliu001** [comment]
> This PR does not respect the contribution guidelines (https://github.com/Kotlin/kotlinx.coroutines/blob/master/CONTRIBUTING.md#submitting-prs), but more importantly, it's also not the change we'd like to introduce, as this can easily be expressed already by applying `buffer()`.

Having to apply `buffer()` as the consumer of the API requires prior knowledge of this potential blocking behavior, i believe the framework should have buffer(UNLIMITED) by default. 

Shall we still integrate the UNLIMITED buffer somewhere?

**Comment by qwwdfsad** [comment]
Among other things, `UNLIMITED` buffer means unlimited queue size and unlimited memory consumption that we would very much like to avoid

**Comment by Ericliu001** [comment]
> Among other things, `UNLIMITED` buffer means unlimited buffer size and unlimited memory consumption that we would very much like to avoid.

I think in this situation it's very "choosing your poison": either blocking the thread or consuming more memory. In Rx, it has chosen the later https://github.com/ReactiveX/RxJava/blob/3.x/src/main/java/io/reactivex/rxjava3/subjects/BehaviorSubject.java 

```
 if (emitting) {
                        AppendOnlyLinkedArrayList<Object> q = queue;
                        if (q == null) {
                            q = new AppendOnlyLinkedArrayList<>(4);
                            queue = q;
                        }
                        q.add(value);
                        return;
                    }
```

**Comment by psteiger** [comment]
Related to #3282

**Comment by dkhalanskyjb** [comment]
> Having to apply buffer() as the consumer of the API requires prior knowledge of this potential blocking behavior

Likewise, if there was no blocking behavior, your message could be rephrased as "having to apply `buffer()` as the consumer of the API requires prior knowledge of this potential unbounded memory consumption." In any case, someone will miss something by not reading the documentation.

> dangerous, especially on single-threaded, immediate-dispatchers contexts.

What's good about these contexts is that usually, the problem is visible immediately during development and can be fixed. On the other hand, an OOM can be hidden, silently sneaking into production.

**Comment by psteiger** [comment]
@dkhalanskyjb I think it's fair to notice what I believe is an inconsistency in the way kotlinx.coroutines handles `Observable` <> coroutines interop, then: 

`ObservableSource<T>.collect { }` already uses an `UNLIMITED` channel + `trySend` under the hood, which is what I would also expect for `asFlow().collect { }` (and which I believe is a saner and safer default than `BUFFERED` + `trySendBlocking`:

```
public suspend inline fun <T> ObservableSource<T>.collect(action: (T) -> Unit): Unit =
    toChannel().consumeEach(action)

@PublishedApi
internal fun <T> ObservableSource<T>.toChannel(): ReceiveChannel<T> {
    val channel = SubscriptionChannel<T>()
    subscribe(channel)
    return channel
}

private class SubscriptionChannel<T> :
    BufferedChannel<T>(capacity = Channel.UNLIMITED), Observer<T>, MaybeObserver<T>
{
  // ...
    override fun onNext(t: T & Any) {
        trySend(t) // Safe to ignore return value here, expectedly racing with cancellation
    }
  // ...
}
```

**Comment by dkhalanskyjb** [comment]
@psteiger, here are the incompatible things:
* The way of kotlinx-coroutines' `Flow`, where we mostly use channels with limited buffers,
* And the way RxJava (in particular, `ObservableSource`) works, which is either to use unlimited stack space and process all emissions immediately or to use unbounded buffers.

There are two intended use cases for `kotlinx-coroutines-rx2`: either someone knows RxJava well but needs to interface with coroutines, or they know `kotlinx-coroutines` well and need to interface with RxJava.

When converting an RxJava entity to a kotlinx-coroutines entity, we must introduce *some* inconsistency: either between a typical `Flow` and the one from RxJava, or between an RxJava entity and the `Flow` received from it. We chose the latter approach: when converting to a kotlinx-coroutines entity, you now subscribe to how we do things here. That's the behavior that the people well-versed in `kotlinx-coroutines` would expect. `ObservableSource.collect`, on the other hand, is not fully in the kotlinx-coroutines world, it's not a converter but an extension function on `ObservableSource`, so it's kept close to what RxJava folks would want.

Luckily, as stated in https://github.com/Kotlin/kotlinx.coroutines/issues/3979#issuecomment-1850154108, the inconsistency between `Flow` and RxJava is easy to mitigate. If you want to change your failure mode, you have a way to do so.

**Comment by psteiger** [comment]
@dkhalanskyjb Thanks for sharing the design details, and overall I find them reasonable. But I still maintain the position for some change here (either in impl, or in docs).

>  If you want to change your failure mode, you have a way to do so.

No one wants to fail with a deadlock, but unfortunately it's far **too easy** to use `ObservableSource.asFlow()` in specific contexts without realizing the risk. It's a default that is dangerous in specific contexts; versus some other potential default that is safe against deadlocks in all contexts.

If the end decision is to keep the implementation, I'd call for an emphasized warning on `asFlow` docs on which particular cases `asFlow` usage can be dangerous.

**Comment by Mustafaubaid4** [comment]
Thanks w

**Pull request closed without merging**
