### PR TITLE
feature: Add setup

### PR DESCRIPTION
**Pull request by AdamSHurwitz**
• Gradle implementation 
• Link to latest library release/version

### CODE REVIEW

**Comment by elizarov** [comment]
Sorry, but this is not consistent with any of the other integration modules we have. We consistently have setup instructions only in the top-level README.md.

**Comment by AdamSHurwitz** [comment]
That makes sense. Would the Play Services setup instructions be a better fit under the top-level README.md's _Using in your projects_ section as an H3?

**Comment by qwwdfsad** [comment]
@AdamSHurwitz thanks for the input!
Unfortunately, we cannot add an instruction on how to include each particular module into dependencies as it will bloat all our documentation for no good reason. If one knows how to include one jar into dependencies, the other ones shouldn't be a big deal.

We will think about how to improve the situation here and probably will add a link with the list of all modules

**Comment by AdamSHurwitz** [comment]
> A link with the list of all modules

This is a great idea! Thank you for the feedback.

**Pull request closed without merging**
