### PR TITLE
Use new Kotlin/JS plugin

### PR DESCRIPTION
**Pull request by turansky**
Part of #1938

### CODE REVIEW

**Comment by elizarov** [comment]
Look good to me. Note, that the new Kotlin/JS has build-in Webpack support and it should be possible to completely get rid of the custom node configuration in `gradle/node-js.gradle`.

**Comment by turansky** [comment]
Next 2 steps after this PRs:
1. Use new MPP plugin for `core`
2. Use `build/distributions` in examples 
2.1. Remove old DCE

@skuzmich Could I skip your change request in this case (CR will be removed in step 2)?

**Comment by turansky** [comment]
> Note, that the new Kotlin/JS has build-in Webpack support and it should be possible to completely get rid of the custom node configuration in `gradle/node-js.gradle`.

One of the goal of this PR - simplify migration to Kotlin DSL (no `gradle/node-js.gradle` == no migration required)

**Comment by skuzmich** [comment]
If kotlinx.coroutines maintainers are OK with temporarily breaking 1.4 builds I can lift the change request.
cc @elizarov

**Pull request merged**
