### PR TITLE
Preserve mutex invariant: throw ISE when incorrect access with owenr is detected

### PR DESCRIPTION
**Pull request by qwwdfsad**

### CODE REVIEW

**Comment by qwwdfsad** [comment]
LGTM (I cannot review this as I'm the author of PR).

I'll merge it tomorrow as soon as I have a proper GH issue to follow

**Review by ndkoval — APPROVED** [review]

**Comment by ndkoval** [comment]
Approved 😄

**Comment by ndkoval** [comment]
Notably, this PR does not fix non-linearizability when using owner-s.

**Comment by qwwdfsad** [comment]
https://github.com/Kotlin/kotlinx.coroutines/issues/3626

**Pull request merged**
