### PR TITLE
Version 1.4.1

### PR DESCRIPTION
**Pull request by elizarov**
This is a patch release with an important fix to the `SharedFlow` implementation.

* SharedFlow: Fix scenario with concurrent emitters and cancellation of subscriber (#2359, thanks to @vehovsky for the bug report).

### CODE REVIEW

**Comment by SteinerOk** [comment]
Files for Version 1.4.1 is still unavailable :(

**Comment by vehovsky** [comment]
I've been wondering about the same. I've build a SNAPSHOT myself which I've been testing and did not experience any crash since.

**Comment by elizarov** [comment]
It is in process. Already uploaded to bintray, soon will be in Maven Central.

**Comment by Thomas-Vos** [comment]
@elizarov could you release a native-mt version for 1.4.1, please?

**Pull request merged**
