### PR TITLE
Create NestedLaunchesTest.kt

### PR DESCRIPTION
**Pull request by ptmt**
Should a test like this pass, or should not by design or did I do something wrong?

### CODE REVIEW

**Comment by qwwdfsad** [comment]
It should and it passes.
Why do you think it should not?

Though I do not recommend invoking code in place in `dispatch` **and** return `true` from `isDispatchNeeded`.

**Comment by ptmt** [comment]
Sorry, I copied the dispatcher from another test in `DelayExceptionTest` by mistake. I replaced it with `Dispatcher.Main` which uses `DefaultExecutor` and fails on `takeEventLoop()`.

**Comment by qwwdfsad** [comment]
Are you talking about native?
Yes, it is expected.
`runBlocking` exits prematurely because your `launch` has a completely different scope and `runBlocking` does not know about that.

In order ot fix that replace `CoroutineScope(dispatcher).launch(dispatcher)` with `launch(dispatcher)` and join on your task

In the future please create an issue for that instead of PR.

**Comment by ptmt** [comment]
Sorry, silly me! It's indeed very obvious, I shouldn't have posted it.

**Pull request closed without merging**
