### PR TITLE
Mention that the copied exception's message must be like the original

### PR DESCRIPTION
**Pull request by adamschoenemann**
Just a quick fly-by PR as a suggestion on including this information.

### CODE REVIEW

**Comment by elizarov** [comment]
I am not sure such a strong wording is really needed. Nothing is going to break inside coroutines machinery is the copied exception message is different from the original, so an emphasis on "must" does not seem to be warranted here. I think it is better to rephrase it as a recommendation.

**Comment by adamschoenemann** [comment]
I'm not married to the wording at all here.
But the point I wanted to come across was that it's *not* gonna attempt to restore the stack if the message is not the same as copied exception.
As per this line https://github.com/Kotlin/kotlinx.coroutines/blob/d7de5f5ba66a8d005e5cbd03b18522112303fd54/kotlinx-coroutines-core/jvm/src/internal/StackTraceRecovery.kt#L70

**Comment by elizarov** [comment]
Good point. That should be added to the docs. That is, the explanation should mentation that the same message is a prerequisite for the stack recovery mechanism.

**Comment by adamschoenemann** [comment]
Exactly :)

**Comment by adamschoenemann** [comment]
Should I close this MR and open an issue instead or what would you prefer?

**Comment by elizarov** [comment]
It just needs a bit rephrasing and clarification on why the same message is needed. No need to close PR. It can be amended.

**Comment by qwwdfsad** [comment]
Thanks! This PR triggered me to investigate the exception message comparison and uncovered #2749.

This PR is superseded by #2749

**Pull request closed without merging**
