### PR TITLE
Fix more typos; reword some phrases; add "job:" to textual output in …

### PR DESCRIPTION
**Pull request by Inego**
…examples

to better differentiate between the "main" and "job" coroutines

### CODE REVIEW

**Comment by Inego** [comment]
I guess I'm doing something wrong...

```
> Task :kotlinx-coroutines-android:dokka FAILED
:kotlinx-coroutines-android:dokka (Thread[Task worker for ':',5,main]) completed. Took 3.257 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kotlinx-coroutines-android:dokka'.
> Guice provision errors:

  1) Error injecting constructor, java.lang.RuntimeException: Exception while loading package-list from ExternalDocumentationLinkImpl(url=https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/, packageListUrl=file://G:/Projects/github/Inego/kotlinx.co
routines/kotlinx-coroutines-core/build/dokka/kotlinx-coroutines-core/package-list)
    at org.jetbrains.dokka.ExternalDocumentationLinkResolver.<init>(ExternalDocumentationLinkResolver.kt:27)
    at org.jetbrains.dokka.ExternalDocumentationLinkResolver.class(ExternalDocumentationLinkResolver.kt:27)
    while locating org.jetbrains.dokka.ExternalDocumentationLinkResolver
      for parameter 4 at org.jetbrains.dokka.DeclarationLinkResolver.<init>(DeclarationLinkResolver.kt:13)
    while locating org.jetbrains.dokka.DeclarationLinkResolver
      for parameter 0 at org.jetbrains.dokka.PackageDocs.<init>(PackageDocs.kt:13)
    at org.jetbrains.dokka.PackageDocs.class(PackageDocs.kt:12)
    while locating org.jetbrains.dokka.PackageDocs
```

**Comment by Inego** [comment]
I'm on Windows and here's what my gradlew.bat is using:

```
------------------------------------------------------------
Gradle 4.10
------------------------------------------------------------

Build time:   2018-08-27 18:35:06 UTC
Revision:     ee3751ed9f2034effc1f0072c2b2ee74b5dce67d

Kotlin DSL:   1.0-rc-3
Kotlin:       1.2.60
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_212-8u ( 25.212-b03)
OS:           Windows 10 10.0 amd64
```

**Comment by elizarov** [comment]
> I guess I'm doing something wrong...

You did right, but there was an intermittent problem with loading package-list for Android docs, as it seems. We need to fix it, though. This bothers me from time time to, too. Here is an issue for it: #648

**Comment by Inego** [comment]
One more thing Gradle cusses at is:
```
Unknown host 'G'.

Please ensure the host name is correct. If you are behind an HTTP proxy, please configure the proxy settings either in IDE or Gradle.
```

It must be the "G" from the local file path `packageListUrl=file://G:/Projects/github/Inego/kotlinx.co
routines/kotlinx-coroutines-core/build/dokka/kotlinx-coroutines-core/package-list`.

**Comment by Inego** [comment]
Knit done, changes committed.

**Comment by elizarov** [comment]
Thanks!

**Pull request merged**
