### PR TITLE
Fix ABSTRACT_MEMBER_NOT_IMPLEMENTED compilation with never Kotlin

### PR DESCRIPTION
**Pull request by nikitabobko**
The compilation started failing after KT-59739

### CODE REVIEW

**Comment by nikitabobko** [comment]
MR in kotlin https://jetbrains.team/p/kt/reviews/11038/timeline

**Comment by nikitabobko** [comment]
The [document](https://jetbrains.team/p/kti/repositories/kotlin-teamcity-build/files/.teamcity/common/buildtypes/tests/userprojects/mainAggregate/README.md) says that I need to create an MR into `origin/develop`

Is it true? The kotlin aggregator works with `kotlin-community/dev` branch

**Comment by nikitabobko** [comment]
@mshishkina we will need this commit in kotlin-community/dev

**Comment by mshishkina** [comment]
MR must be reviewed also by the library author, merged into origin/develop, then we rebase kotlin-community/dev on it.

**Comment by nikitabobko** [comment]
> MR must be reviewed also by the library author

Ok, then it looks like I need to wait for @dkhalanskyjb accept and merge

**Review by qwwdfsad — APPROVED** [review]

**Review by mshishkina — APPROVED** [review]

**Pull request merged**
