### PR TITLE
Use outputFileProperty instead of outputFile

### PR DESCRIPTION
**Pull request by ilgonmic**
Because of changes in API of compile task

### CODE REVIEW

**Review by qwwdfsad — CHANGES_REQUESTED** [review]
It does not build that implies breaking changes in the plugin.

Please elaborate on why these changes are necessary in the first place and whether the breaking changes are intended

**Comment by ilgonmic** [comment]
Changes with migration from `outputFile` to `outputDirectory` in Gradle plugin are necessary, because can be situation, when users want to use complex module name e.g. (`@foo/bar`). And for these one `outputFile` migrated to 2 properties `outputDir` and `moduleName`.
Apart from that, `outputFile` was deprecated earlier with migration plan to `outputFileProperty` (because of Gradle property API), so there is a plan to leve only property-based inputs and outputs

**Comment by qwwdfsad** [comment]
Thanks, but why is it non-buildable then?

I find it concerning that we have a deprecated API that has no replacement until Kotlin 1.8.0, where the original API is dropped

**Comment by qwwdfsad** [comment]
@ilgonmic can you please provide an update regarding this one?

**Comment by ilgonmic** [comment]
Yes, sorry

It has a replacement. `outputFileProperty` is the replacement, using Gradle Property API.
And it existed during deprecation cycle of `outputFile`

**Comment by qwwdfsad** [comment]
I see, thanks. Please target the PR into `develop` branch and let release team rebase on it in such case

**Comment by ilgonmic** [comment]
Done

**Pull request merged**
